using System;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace ChanthraStudio.Services.Gpu;

/// <summary>
/// Builds the shell script the marketplace runs when the container boots.
///
/// The script does four things, in this order for a reason:
///
///   1. <b>Starts the auth proxy first.</b> Installing ComfyUI and pulling
///      20–35 GB of weights takes 10–40 minutes. If nothing answered during
///      that window the studio could not tell "still warming up" from "dead
///      box", and would either give up on a machine that was fine or keep
///      paying for one that wasn't. The proxy answers from second one and
///      reports the current stage.
///   2. Installs ComfyUI bound to <c>127.0.0.1</c> only.
///   3. Downloads the profile's weights, verifying each one landed.
///   4. Flips the stage to <c>ready</c> once ComfyUI actually responds.
///
/// <b>Why the proxy exists at all:</b> ComfyUI ships with no authentication,
/// and the rented port is reachable from the public internet. Anyone who
/// guessed the URL could queue work on a GPU we are paying for — and ComfyUI
/// can read and write files and install custom nodes, so it is not merely a
/// billing problem. The proxy is the only thing listening publicly; ComfyUI
/// binds to loopback. Requests must carry
/// <c>Authorization: Bearer &lt;token&gt;</c>, compared in constant time.
///
/// The proxy is deliberately a dumb TCP relay after the auth gate: it never
/// parses bodies. That is what lets it carry chunked history responses,
/// multi-gigabyte <c>/view</c> downloads, multipart image uploads, and the
/// <c>/ws</c> progress socket without special-casing any of them.
/// </summary>
public static class GpuProvisioning
{
    /// <summary>Container port the proxy listens on — the only one exposed.</summary>
    public const int ProxyPort = 20000;

    /// <summary>ComfyUI's port, bound to loopback and never exposed.</summary>
    public const int ComfyPort = 8188;

    /// <summary>Status endpoint the studio polls while a worker warms up.</summary>
    public const string StatusPath = "/chanthra/status";

    /// <summary>Mints a 256-bit worker token. One per worker, never reused.</summary>
    public static string NewWorkerToken()
        => Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();

    /// <summary>
    /// Assembles the boot script for one worker.
    /// </summary>
    /// <param name="profile">What to install.</param>
    /// <param name="workerToken">The bearer token this worker will require.</param>
    /// <param name="hfToken">Optional Hugging Face token for gated repos.</param>
    public static string BuildStartScript(GpuModelProfile profile, string workerToken, string? hfToken)
    {
        if (string.IsNullOrWhiteSpace(workerToken))
            throw new ArgumentException("A worker token is required — an unauthenticated ComfyUI on a public port is not something we ship.", nameof(workerToken));

        var downloads = new StringBuilder();
        foreach (var f in profile.Files)
        {
            // Single-quoted shell args; the catalog is app-controlled, but a
            // stray quote in an edited overrides file should break the script
            // loudly rather than splice into it.
            downloads.Append("dl ")
                     .Append(ShellQuote(f.Url)).Append(' ')
                     .Append(ShellQuote(f.Folder)).Append(' ')
                     .Append(ShellQuote(f.FileName)).Append(' ')
                     .Append(f.SizeGb.ToString("0.###", CultureInfo.InvariantCulture))
                     .Append('\n');
        }

        return ScriptTemplate
            .Replace("@@TOKEN@@", ShellQuote(workerToken))
            .Replace("@@HF_TOKEN@@", ShellQuote(hfToken ?? ""))
            .Replace("@@PROXY_PORT@@", ProxyPort.ToString(CultureInfo.InvariantCulture))
            .Replace("@@COMFY_PORT@@", ComfyPort.ToString(CultureInfo.InvariantCulture))
            .Replace("@@PROFILE@@", ShellQuote(profile.Key))
            .Replace("@@DOWNLOADS@@", downloads.ToString().TrimEnd())
            .Replace("@@PROXY_SOURCE@@", ProxySource);
    }

    /// <summary>Wraps a value in single quotes, escaping any it contains.</summary>
    internal static string ShellQuote(string value)
        => "'" + (value ?? "").Replace("'", "'\\''") + "'";

    // =====================================================================
    // Boot script
    // =====================================================================

    private const string ScriptTemplate = """
#!/usr/bin/env bash
# Chanthra Studio — rented worker bootstrap. Generated by GpuProvisioning.
set -uo pipefail

CH_HOME=/opt/chanthra
COMFY=/opt/ComfyUI
mkdir -p "$CH_HOME"
exec >>"$CH_HOME/boot.log" 2>&1
echo "=== chanthra worker boot $(date -u '+%Y-%m-%dT%H:%M:%SZ') ==="

export CHANTHRA_TOKEN=@@TOKEN@@
export CHANTHRA_PROXY_PORT=@@PROXY_PORT@@
export CHANTHRA_COMFY_PORT=@@COMFY_PORT@@
export CHANTHRA_PROFILE=@@PROFILE@@
export HF_TOKEN=@@HF_TOKEN@@

stage()  { printf '%s' "$1" > "$CH_HOME/stage";  echo "[stage] $1"; }
detail() { printf '%s' "$1" > "$CH_HOME/detail"; }
fail()   { printf '%s' "$1" > "$CH_HOME/error"; stage failed; echo "[fail] $1"; }

: > "$CH_HOME/error"
detail ""
stage booting

PY="$(command -v python3 || command -v python)"
if [ -z "$PY" ]; then fail "no python interpreter in the image"; exit 1; fi

# --- 1. auth proxy, before anything slow -----------------------------------
cat > "$CH_HOME/proxy.py" <<'CHANTHRA_PROXY_EOF'
@@PROXY_SOURCE@@
CHANTHRA_PROXY_EOF

"$PY" "$CH_HOME/proxy.py" >>"$CH_HOME/proxy.log" 2>&1 &
echo "[boot] proxy pid $!"

# --- 2. system packages ----------------------------------------------------
stage deps
export DEBIAN_FRONTEND=noninteractive
apt-get update -y >/dev/null 2>&1 || true
apt-get install -y --no-install-recommends git curl ca-certificates ffmpeg >/dev/null 2>&1 || true
if ! command -v git >/dev/null 2>&1; then fail "git unavailable — cannot fetch ComfyUI"; exit 1; fi

# --- 3. ComfyUI ------------------------------------------------------------
stage comfyui
if [ ! -d "$COMFY/.git" ]; then
  git clone --depth 1 https://github.com/comfyanonymous/ComfyUI "$COMFY" \
    || { fail "ComfyUI clone failed"; exit 1; }
fi
"$PY" -m pip install --no-cache-dir --upgrade pip >/dev/null 2>&1 || true
"$PY" -m pip install --no-cache-dir -r "$COMFY/requirements.txt" \
  || { fail "pip install of ComfyUI requirements failed"; exit 1; }

# --- 4. weights ------------------------------------------------------------
stage weights

# dl <url> <models-subfolder> <filename> <expected-GB>
dl() {
  url="$1"; sub="$2"; name="$3"; want_gb="$4"
  dir="$COMFY/models/$sub"
  mkdir -p "$dir"
  detail "$name"
  echo "[dl] $name -> models/$sub"

  auth=()
  if [ -n "${HF_TOKEN:-}" ]; then auth=(-H "Authorization: Bearer $HF_TOKEN"); fi

  if ! curl -fL --retry 5 --retry-delay 5 --retry-connrefused \
            --connect-timeout 30 -C - "${auth[@]}" -o "$dir/$name" "$url"; then
    fail "download failed: $name"
    exit 1
  fi

  # A gated repo or an expired link answers 200 with an HTML page, which
  # lands as a .safetensors that only fails hours later inside a render.
  # Compare against the size the catalog measured and refuse anything short.
  got=$(stat -c %s "$dir/$name" 2>/dev/null || echo 0)
  min=$(awk -v g="$want_gb" 'BEGIN{printf "%d", g*1073741824*0.9}')
  if [ "$got" -lt "$min" ]; then
    fail "$name is $got bytes, expected ~${want_gb}GB — the URL may be gated or moved"
    exit 1
  fi

  # ComfyUI has renamed these folders across versions and different nodes
  # look in different ones. Link rather than copy so it costs no disk.
  case "$sub" in
    diffusion_models) mkdir -p "$COMFY/models/unet" && ln -sf "$dir/$name" "$COMFY/models/unet/$name" ;;
    text_encoders)    mkdir -p "$COMFY/models/clip" && ln -sf "$dir/$name" "$COMFY/models/clip/$name" ;;
  esac
}

@@DOWNLOADS@@

detail ""

# --- 5. run ----------------------------------------------------------------
stage starting
cd "$COMFY"
"$PY" main.py --listen 127.0.0.1 --port "$CHANTHRA_COMFY_PORT" >>"$CH_HOME/comfy.log" 2>&1 &
COMFY_PID=$!
echo "[boot] comfyui pid $COMFY_PID"

# Only report ready once ComfyUI actually answers. Saying "ready" when the
# process merely started would hand the studio a worker that 502s on submit.
for i in $(seq 1 180); do
  if curl -sf --max-time 5 "http://127.0.0.1:$CHANTHRA_COMFY_PORT/system_stats" >/dev/null 2>&1; then
    stage ready
    break
  fi
  if ! kill -0 "$COMFY_PID" 2>/dev/null; then
    fail "ComfyUI exited during startup — see comfy.log"
    exit 1
  fi
  sleep 5
done

if [ "$(cat "$CH_HOME/stage" 2>/dev/null)" != "ready" ]; then
  fail "ComfyUI did not answer within 15 minutes of starting"
  exit 1
fi

wait "$COMFY_PID"
fail "ComfyUI exited"
""";

    // =====================================================================
    // Auth proxy (Python 3 standard library only — no pip at boot time)
    // =====================================================================

    // Five-quote delimiter: the Python below contains its own triple-quoted
    // docstrings, which would otherwise close the literal early.
    private const string ProxySource = """""
# Chanthra Studio worker proxy.
#
# The only publicly reachable listener on this box. Checks a bearer token in
# constant time, then relays raw bytes to ComfyUI on loopback. Because it
# never parses bodies it transparently carries chunked responses, large file
# downloads, multipart uploads and the WebSocket upgrade for /ws.
import hmac
import json
import os
import select
import socket
import socketserver
import sys
import threading

TOKEN = os.environ.get("CHANTHRA_TOKEN", "").encode()
LISTEN_PORT = int(os.environ.get("CHANTHRA_PROXY_PORT", "20000"))
COMFY_PORT = int(os.environ.get("CHANTHRA_COMFY_PORT", "8188"))
PROFILE = os.environ.get("CHANTHRA_PROFILE", "")
HOME = "/opt/chanthra"
MAX_HEAD = 65536


def _read_file(name):
    try:
        with open(os.path.join(HOME, name), "r") as fh:
            return fh.read().strip()
    except OSError:
        return ""


def status_body():
    return json.dumps({
        "stage": _read_file("stage") or "booting",
        "detail": _read_file("detail"),
        "error": _read_file("error"),
        "profile": PROFILE,
        "comfyPort": COMFY_PORT,
    }).encode()


def respond(sock, code, reason, body, ctype="application/json"):
    head = (
        "HTTP/1.1 %d %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %d\r\n"
        "Connection: close\r\n"
        "\r\n" % (code, reason, ctype, len(body))
    ).encode()
    try:
        sock.sendall(head + body)
    except OSError:
        pass


def read_head(sock):
    """Read up to the end of the request headers. Returns (head, leftover)."""
    buf = b""
    while b"\r\n\r\n" not in buf:
        try:
            chunk = sock.recv(4096)
        except OSError:
            return None, b""
        if not chunk:
            return None, b""
        buf += chunk
        if len(buf) > MAX_HEAD:
            return None, buf
    head, rest = buf.split(b"\r\n\r\n", 1)
    return head, rest


def authorized(head):
    # An empty token would make compare_digest trivially satisfiable, so an
    # unconfigured worker refuses everything rather than opening up.
    if not TOKEN:
        return False
    expected = b"Bearer " + TOKEN
    for line in head.split(b"\r\n")[1:]:
        if line[:14].lower() == b"authorization:":
            supplied = line.split(b":", 1)[1].strip()
            # Constant-time: a plain == leaks the shared prefix length via
            # timing, which is enough to walk a token out one byte at a time.
            return hmac.compare_digest(supplied, expected)
    return False


def pump(a, b):
    """Relay bytes both ways until either side hangs up."""
    a.setblocking(True)
    b.setblocking(True)
    socks = [a, b]
    try:
        while True:
            readable, _, broken = select.select(socks, [], socks, 600)
            if broken or not readable:
                return
            for s in readable:
                other = b if s is a else a
                try:
                    data = s.recv(65536)
                except OSError:
                    return
                if not data:
                    return
                try:
                    other.sendall(data)
                except OSError:
                    return
    finally:
        for s in (a, b):
            try:
                s.close()
            except OSError:
                pass


class Handler(socketserver.BaseRequestHandler):
    def handle(self):
        client = self.request
        client.settimeout(120)

        head, rest = read_head(client)
        if head is None:
            return

        if not authorized(head):
            respond(client, 401, "Unauthorized", b'{"error":"bad or missing bearer token"}')
            return

        try:
            path = head.split(b"\r\n", 1)[0].split(b" ")[1]
        except IndexError:
            respond(client, 400, "Bad Request", b'{"error":"malformed request line"}')
            return

        if path.startswith(b"/chanthra/status"):
            respond(client, 200, "OK", status_body())
            return

        try:
            upstream = socket.create_connection(("127.0.0.1", COMFY_PORT), timeout=10)
        except OSError:
            # ComfyUI is not up yet. Answering with the warm-up stage (rather
            # than a bare connection error) is what lets the studio show real
            # progress instead of guessing whether the box is alive.
            respond(client, 503, "Service Unavailable", status_body())
            return

        try:
            upstream.sendall(head + b"\r\n\r\n" + rest)
        except OSError:
            try:
                upstream.close()
            except OSError:
                pass
            return

        client.settimeout(None)
        pump(client, upstream)


class Server(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


if __name__ == "__main__":
    if not TOKEN:
        sys.stderr.write("CHANTHRA_TOKEN is empty — refusing to start an open proxy\n")
        sys.exit(1)
    Server(("0.0.0.0", LISTEN_PORT), Handler).serve_forever()
""""";
}
